version: '3.8'

services:
  gradesense-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER:-gemini}
      - API_KEYS=${API_KEYS:-test-key,demo-key}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./test_samples:/app/test_samples
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
